#! /bin/bash
cd /home/ec2-user/AWS/aws-java-loadbalancer/
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT  --to-port 8080
sudo service iptables save
sudo rm -r target/
mvn clean compile exec:java
